name: Admin CI/CD

on:
  push:
    branches: [main, develop]
    paths: ['admin/**']
  pull_request:
    branches: [main, develop]
    paths: ['admin/**']

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'admin/package-lock.json'

      - name: Install dependencies
        run: |
          cd admin
          npm ci

      - name: Run ESLint
        run: |
          cd admin
          npm run lint

      - name: Check Prettier formatting
        run: |
          cd admin
          npm run format:check

  test:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'admin/package-lock.json'

      - name: Install dependencies
        run: |
          cd admin
          npm ci

      - name: Run tests
        run: |
          cd admin
          npm test -- --watch=false --browsers=ChromeHeadless

  build:
    runs-on: ubuntu-latest
    needs: [lint-and-format, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'admin/package-lock.json'

      - name: Install dependencies
        run: |
          cd admin
          npm ci

      - name: Build application
        run: |
          cd admin
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: admin-build
          path: admin/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: admin-build
          path: admin/dist

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
          entryPoint: ./admin
